[yamui] Suppress compilation warnings
minui/graphics.c:96:4: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
minui/graphics.c:98:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’

Assume that the code layout matches the intent and add missing {} braces.

minui/resources.c:67:29: warning: variable ‘result’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]

Assume that this is optimization issue that can be avoided by marking
the variable as volatile and thus not eligible for storage in a register.

minui/graphics_drm.c:71:38: warning: unused parameter ‘backend’ [-Wunused-parameter]
minui/graphics_drm.c:307:43: warning: unused parameter ‘backend’ [-Wunused-parameter]
minui/graphics_drm.c:381:43: warning: unused parameter ‘backend’ [-Wunused-parameter]
minui/graphics_drm.c:392:37: warning: unused parameter ‘backend’ [-Wunused-parameter]

"Use" the parameters by involving them in dummy casts.

minui/graphics_drm.c:316:15: warning: implicit declaration of function ‘asprintf’; did you mean ‘vsprintf’? [-Wimplicit-function-declaration]

Software that relies on GNU features might as well define _GNU_SOURCE
globally from Makefile to avoid subtle issues like e.g. missing prototypes.

minui/graphics_drm.c:402:13: warning: initialization of ‘GRSurface * (*)(struct minui_backend *, _Bool)’ {aka ‘struct <anonymous> * (*)(struct minui_backend *, _Bool)’} from incompatible pointer type ‘GRSurface * (*)(minui_backend *)’ {aka ‘struct <anonymous> * (*)(struct minui_backend *)’} [-Wincompatible-pointer-types]
minui/graphics_drm.c:402:13: note: (near initialization for ‘drm_backend.init’)

Make drm_init() function match the expected backend callback template.

yamui-tools.c:99:36: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 245 [-Wformat-truncation=]

Add buffer too small check.

Signed-off-by: Simo Piiroinen <simo.piiroinen@jolla.com>